### ISSUE TITLE
[feature request] Emit error back to the stream

### ISSUE THREAD

**Issue by tsouza** [Jason3S/rx-stream#1]
Could it be possible to add a configuration option so it emits any error to the resulting stream instead of just closing it?

I suppose should be fairly simple with something like the following right below line https://github.com/Jason3S/rx-stream/blob/master/src/rxToStream.ts#L22:
```js
if (emitError && err)
  readable.emit('error', err);
```

**Comment by Jason3S** [comment]
Sorry about taking so long. I've been busy with family.
I have merged your pull request and published.

**Comment by benlesh** [comment]
Seems like this can be closed?

**Comment by tsouza** [comment]
For me is fine. I've worked around the issue.
