### ISSUE TITLE
Why is subscribe() not in constructor() ? Moving it there solved a bug I had

### ISSUE THREAD

**Issue by vibl** [Jason3S/rx-stream#106]
I spent a few hours trying to understand a hard-to-debug problem in `rxToStream` where the source observable was completing before emitting values.

I ended up solving it by moving `this._subscription = this._source.subscribe(...)` in `constructor()`.

I'd rather not fork this lib though.

Why is the subscription made in the first `_read()` instead of `constructor()` ?

**Comment by Jason3S** [comment]
@vibl,

The late binding was intentional. It follow the same paradigm as Observables, to stay cold until a subscribe happens. This is also how streams work. A stream isn't read until it is attached/piped to a writeable stream.

Did you try using a ReplaySubject?

**Comment by vibl** [comment]
Readable streams start paused but that doesn't prevent them from receiving data from their source before being read. An `http.get`, for example, downloads data as soon as it is called, event if `response.on("data"...) or response.pipe()` is only called later.

This is what should be expected when the source of the stream is sending data without waiting, such as a web server.

Similarly, in the case of `rxToStream`, I would expect the stream to subscribe and receive values from the source observable as soon as the stream is created, so it can miss initial values if the observer is a subject. Or create bugs like the one I had.

In the case of `createReadStream() `, the situation is different: the data is at rest and the process is retrieving it actively (instead of receiving it passively once requested), which is why the reading process is started lazily.

**Comment by Jason3S** [comment]
@vibl,

I can see your point. Both behaviors are valid and have their place.

By attaching it in the constructor, there is potential for the internal buffer to grow very large before a reader is attached.

I can see adding a `lazy` option to the constructor, giving the caller the choice. By default `lazy` would need to be `true` or it will break existing code.

**Comment by vibl** [comment]
Yes, that would be great :-)

Thank you for offering this lib anyway!

**Comment by vibl** [comment]
Great.

I read your commit. Shouldn't the ` this.subscribe();` be inside a condition `if (!this._subscription)` ? Otherwise, there's going to be multiple subscriptions if I'm not mistaken.
