### ISSUE TITLE
Cannot use stdin & stdout together

### ISSUE THREAD

**Issue by AndreyNikiforov** [Jason3S/rx-stream#6]
Found this wonderful lib recently and trying to combine both "ends" into one simple rxjs pipeline:

```
const { map } = require('rxjs/operators'); 
const { rxToStream, streamToStringRx } = require('rxjs-stream');

const ob = streamToStringRx(process.stdin)
.pipe(
    map(l => l.toUpperCase()),
);

rxToStream(ob).pipe(process.stdout);
```

To produces no output when executed as `echo 'abc' | node <myfilename>.js`

Am I missing anything and it is not supposed to work that way?

```
node --version
v10.8.0
```

package.json deps:
```
    "rxjs": "^6.3.1",
    "rxjs-stream": "^3.0.0"
```

**Comment by Jason3S** [comment]
Thank you for bringing this up. I need to setup a test for that.

**Comment by Jason3S** [comment]
This should be fixed.
